### ISSUE TITLE
Mobile NavBar

### ISSUE THREAD

**Issue by DavidAylaian** [OriginalAndCreativeName/Applied-Visuals-Site#3]
It's pretty broken.

**Comment by ftf841** [comment]
it works fine on desktop though

**Comment by DavidAylaian** [comment]
@ftf841 that's because you don't ever see the mobile NavBar on desktop unless you make your window small.

**Comment by baconsuperguy** [comment]
When did you download Materialize?  They changed up the mobile navbar and the code for it a while back

**Comment by DavidAylaian** [comment]
Mobile NavBar removed in f9c64772aeec1c4805afcac88f15428f9811c1fd because it was a mess and we need to start from scratch

**Comment by DavidAylaian** [comment]
We're not closing it until it's fixed.

**Comment by DavidAylaian** [comment]
"Fixed" problem for tablets in 9b2ec3afe53ff14a217b24f21f52f75c5c01e174 by making them use the desktop navbar.
